image:
  file: .gitpod.Dockerfile
tasks:
  - name: STARTING 
    before: |
      nvm install 14.17.0
      nvm alias default 14.17.0
      npx @angular/cli analytics off
      npm iinstall -g @angular/cli && firebase-tools
      npm install
    # before: |  
      # echo "Updating npm"
      # npm install -g npm@latest
      # echo "Installing tools…"
      # npm install -g firebase-tools && @angular/cli
    init: |
      echo "Installing dependencies…"
      npm install
    command: |
      echo "Serve project"
      npm start
  - name: DEPLOY
    command: |
      echo "Build & deploy"
      ng build --prod
      firebase login --no-localhost
      firebase deploy --only firestore && hosting

