image:
  file: .gitpod.Dockerfile
tasks:
  - name: STARTING 
    before: |
      echo "✅ BEFORE | PREBUILT & WORKSPACE: Define node version, install angular and firebase"
      nvm install 12.20.2
      nvm alias default 12.20.2
      npx @angular/cli analytics off
      npm install -g @angular/cli
      npm install -g firebase-tools
    init: |
      echo "✅ INIT | PREBUILT: Installing dependencies…"
      npm install
      gp sync-done start
    command: |
      echo "✅ COMMAND | WORKSPACE: Serve project"
      npm start
  - name: DEPLOY
    init: gp sync-await start
    command: |
      echo "✅ COMMAND | WORKSPACE: Build & deploy"
      ng build --prod
      firebase login --no-localhost
      firebase deploy --only firestore && hosting
